- README.md
To the main 📖 so 👨‍👩‍👧‍👦 don't have to 👓 around for them
> Add instructions for running just the frontend locally

- ui/frontend/index.scss
Clicky clicky hover hover active active prada
Those basic buttons wear that shit but i don't even botha
> Better buttons

- README.md
This is analogue to what was already done in the `Build the containers` section.
> Keep track of CWD in README

- ui/frontend/Editor.jsx
> Vim-mode's :w should execute the code

- ui/frontend/Output.jsx
- ui/frontend/reducers/output.js
> Show basic progress for the formatting operation

- ui/src/sandbox.rs
> Find the assembly and LLVM IR in nightly (1.15)

- compiler/beta/Dockerfile
- compiler/nightly/Dockerfile
- compiler/stable/Dockerfile
- tests/spec/features/backtrace_spec.rb
- tests/spec/features/compilation_modes_spec.rb
- tests/spec/features/compilation_targets_spec.rb
- tests/spec/features/crate_types_spec.rb
- tests/spec/features/editor_types_spec.rb
- tests/spec/features/highlighting_error_output_spec.rb
- tests/spec/features/multiple_channels_spec.rb
- tests/spec/features/sharing_with_others_spec.rb
- tests/spec/features/tests_spec.rb
- tests/spec/features/tools_spec.rb
- ui/frontend/Header.jsx
- ui/frontend/actions.js
- ui/frontend/reducers.js
- ui/src/data.rs.in
- ui/src/main.rs
- ui/src/sandbox.rs
> Support crate types other than binary

- top-crates/Cargo.lock
- top-crates/Cargo.toml
> Update to released toml-0.3

- tests/spec/features/compilation_targets_spec.rb
- ui/frontend/Header.jsx
- ui/frontend/Output.jsx
- ui/frontend/actions.js
- ui/frontend/reducers/output.js
- ui/src/main.rs
- ui/src/sandbox.rs
> Add MIR output (on nightly)

- ui/frontend/index.scss
> Avoid collision between the dropdown menu and the editor text

- ui/frontend/Configuration.jsx
- ui/frontend/Output.jsx
- ui/frontend/Playground.jsx
- ui/frontend/actions.js
- ui/frontend/index.js
- ui/frontend/index.scss
- ui/frontend/reducers.js
This reverts commit 71e4b2aa2bcab1c9dac406e4d0a9338ad4c5ce9a.
> Revert "Hemisphere support"

- ui/frontend/AdvancedEditor.jsx
> Enforce that brace is loaded before the keybinding or theme

- ui/frontend/reducers/output.js
> Save the current channel when creating a Gist

- tests/spec/features/compilation_targets_spec.rb
- ui/frontend/Header.jsx
> MIR is now always available

- ui/src/main.rs
> Handle the evaluate.json route for in-page requests and responses

- tests/spec/features/compilation_targets_spec.rb
- ui/src/sandbox.rs
> Show compilation errors for alternate output formats

- tests/spec/features/compilation_targets_spec.rb
- ui/frontend/Configuration.jsx
- ui/frontend/actions.js
- ui/frontend/local_storage.js
- ui/frontend/reducers.js
- ui/src/main.rs
- ui/src/sandbox.rs
> Support ASM flavor choice

- ui/src/main.rs
> Report evaluate.json errors inline in the report key

- ui/frontend/reducers.js
> Expand regex to match #![crate_type = "lib"] on any line

- ui/src/main.rs
> Allow local copies of The Rust Programming Language to also evaluate code

- compiler/build.sh
- compiler/rustfmt/Dockerfile
It appears that this gets updated more frequently.
> Update to rustfmt-nightly

- ui/frontend/Header.tsx
- ui/frontend/actions.ts
- ui/frontend/index.tsx
- ui/frontend/reducers/index.ts
- ui/frontend/reducers/versions.ts
- ui/frontend/selectors/index.ts
- ui/frontend/types.ts
- ui/src/main.rs
- ui/src/sandbox.rs
> Show channel versions as a tooltip

- ui/frontend/AdvancedEditor.tsx
I misread the react-ace changelog! However, this solution is a lot
cleaner.
Closes #223
> Resize the Ace editor when the focus changes

- compiler/base/Dockerfile
- compiler/base/cargo-wasm
- compiler/base/postinstall.sh
- tests/spec/features/compilation_targets_spec.rb
- ui/frontend/Header.tsx
- ui/frontend/Output.tsx
- ui/frontend/actions.ts
- ui/frontend/reducers/output/index.ts
- ui/frontend/reducers/output/meta.ts
- ui/frontend/reducers/output/wasm.ts
- ui/frontend/selectors/index.ts
- ui/src/main.rs
- ui/src/sandbox.rs
> Basic support for WebAssembly

- ui/frontend/Header.tsx
- ui/frontend/index.scss
Resolves #236 
- make WASM button always visible, add tooltip when WASM compilation is not available
- adjust styles for disabled buttons
> Make WASM button disabled instead of hidden

- ui/src/asm_cleanup.rs
- ui/src/main.rs
- ui/src/sandbox.rs
Remediates the following issues identified by clippy:
[const_static_lifetime](https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#const_static_lifetime)
[filter_next](https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#filter_next)
[single_match](https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#single_match)
[single_char_pattern](https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#single_char_pattern)
[option_map_or_none](https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#option_map_or_none)
[match_ref_pats](https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#match_ref_pats)
[needless_borrow](https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#needless_borrow) …
> Fix issues identified by clippy

- compiler/base/cargo-wasm
- compiler/base/postinstall.sh
* Install wasm-gc from crates.io (it's published now!)
* Turn on LTO in release builds for wasm to make it extra small
> Small wasm tweaks

- ui/Cargo.lock
- ui/Cargo.toml
- ui/src/main.rs
https://github.com/emk/rust-musl-builder#making-openssl-work
> Probe for OpenSSL configuration

- ui/src/sandbox.rs
Works around https://github.com/rust-lang-nursery/rustfmt/issues/2543
> Restore Rustfmt support

- tests/spec/features/highlighting_error_output_spec.rb
- ui/frontend/highlighting.ts
> Link "see issue #....."

- ui/frontend/highlighting.ts
> Match error and warning text only when they start the line of output

- ui/frontend/advanced-editor.ts
> Load the ACE searchbox component

- tests/spec/features/url_parameters_spec.rb
- ui/frontend/Icon.tsx
- ui/frontend/actions.ts
- ui/frontend/reducers/code.ts
- ui/frontend/reducers/crates.ts
- ui/frontend/reducers/output/clippy.ts
- ui/frontend/reducers/output/format.ts
- ui/frontend/reducers/output/gist.ts
- ui/frontend/reducers/output/meta.ts
- ui/frontend/reducers/output/sharedStateManagement.ts
- ui/frontend/reducers/page.ts
- ui/frontend/reducers/position.ts
- ui/frontend/reducers/versions.ts
> Preserve gist params

- tests/spec/features/sharing_with_others_spec.rb
- ui/frontend/Output/Gist.tsx
- ui/frontend/actions.ts
- ui/frontend/package.json
- ui/frontend/reducers/output/gist.ts
- ui/frontend/selectors/index.ts
- ui/frontend/yarn.lock
I am very sorry if I am violating every rule imaginable... I don't even know what language this is written in. I just looked at whatever was going on and copied stuff.
> Add a link for producing issues

- ui/frontend/Output.tsx
- ui/frontend/actions.ts
- ui/frontend/highlighting.ts
- ui/frontend/reducers/code.ts
- ui/frontend/reducers/output/format.ts
- ui/frontend/reducers/output/meta.ts
> Show errors originating from rustfmt

- ui/frontend/highlighting.ts
> Sometimes rustfmt returns an error location of only a line number

- ui/frontend/local_storage.ts
- ui/frontend/session_storage.ts
- ui/frontend/storage.spec.ts
- ui/frontend/storage.ts
> Gracefully handle security settings preventing local/session storage

- ui/frontend/AdvancedEditor.tsx
> Show autocomplete crates only when the line starts with use

- compiler/clippy/Dockerfile
- compiler/miri/Dockerfile
- compiler/rustfmt/Dockerfile
- ui/frontend/actions.ts
- ui/src/main.rs
- ui/src/sandbox.rs
Note that I have no idea what I am doing here.  I guessed my way through the Rust part of this until it looked toughly like what compile requests do, and then it got even worse for the TypeScript part as I have never read or written a single line of TypeScript before.^^  I hope this makes some sense... I wouldn't know how to test any of this.
Fixes https://github.com/integer32llc/rust-playground/issues/429
> Make Miri honor selected edition

- tests/Gemfile
- tests/Gemfile.lock
- tests/spec/features/tools_spec.rb
- tests/spec/features/url_parameters_spec.rb
- ui/frontend/actions.ts
- ui/frontend/selectors/index.ts
- ui/src/main.rs
- ui/src/sandbox.rs
> Support edition and crate type when running Clippy

- compiler/miri/Dockerfile
> install miri via rustup

- ui/README.md
I've closed the issue but this is related to fix  #480 🙇
> Add troubleshooting for Docker mount denied on mac

- ui/frontend/actions.ts
- ui/frontend/selectors/index.ts
- ui/src/main.rs
- ui/src/sandbox.rs
> Make rustfmt honor selected edition

- ui/frontend/Configuration.tsx
> Use && operator for conditional rendering

- ui/README.md
This took me an embarrassingly long time to figure out.
> Document PLAYGROUND_CORS_ENABLED

- ui/frontend/AdvancedEditor.tsx
When we hit "return" when the cursor is indented, Ace generates two events:
1. The newline
2. The indentation
These events flow through Redux and are both applied to the editor as
they might have come from any other source. However, by the time we
apply them, Ace's internal state is up-to-date, so it looks like we
are reverting the changes, causing all sorts of strange behavior.
Back-to-back events can also come from "undo" / "redo" commands or
multi-cursor editing.
As a pretty good bandaid, this commit batches up the events before a
RequestAnimationFrame and only submits the last one. This isn't
*perfect* as mashing on the keyboard can still generate some issues.
Fixes #496
> Debounce back-to-back change events from Ace

- ui/frontend/AdvancedEditor.tsx
This adds stronger protections against spurious events being generated
from the advanced editor as well as attempting to ignore the events
generated by the editor from being re-applied to the editor.
Fixes #498
> Prevent letters from appearing after the cursor when typing quickly

- ui/frontend/Header.tsx
- ui/frontend/HeaderButton.tsx
HeaderButton component can be used for creating buttons with right icon.
> Remove RightIconButton component

- ui/frontend/AdvancedEditor.tsx
- ui/frontend/ConfigMenu.tsx
- ui/frontend/Configuration.tsx
- ui/frontend/actions.ts
- ui/frontend/local_storage.ts
- ui/frontend/reducers/configuration.ts
- ui/frontend/types.ts
> Add config option to disable automatic pairing of characters

- ui/frontend/AdvancedEditor.tsx
With the addition of the linting rules, we started running the editor
side effects whenever the callback passed to `useEditorProp` changed,
which caused inefficiency as well as unintended effects. This
manifested as the cursor jumping to the beginning of file after typing
any character.
Fixes #527
> Memoize the Ace editor property callbacks.

- ui/src/sandbox.rs
When switching to non-root containers, the output directory
automatically created by Docker is owned by root and not writable by
non-root, which breaks all the tools where we have to read a
file (rustfmt, assembly output, etc.)
This doesn't seem to be a problem when using docker-machine, probably
due to the indirection that is automatically performed.
> Proactively create the output directory and make it world-writable

- ui/src/sandbox.rs
Rustfmt writes directly to the input file. Same rationale as
f2bb099dc6b06adcbf12f01863b7ee906ecb1eeb.
> Make the input file world-writable as well

- compiler/base/Cargo.toml
- compiler/base/crate-information.json
I'm planning to send the PR about rustfmt.toml, but CI is failed now.
So I send this PR.
> Update version of yanked time crate

- ui/src/gist.rs
Related to https://github.com/integer32llc/rust-playground/issues/542
> Change GitHub Gist creation to be private

- ui/frontend/yarn.lock
> Bump Ace to highlight async/await keyword

- ui/frontend/selectors/index.spec.ts
- ui/frontend/selectors/index.ts
> Support `const fn main`

- .travis/compile-frontend.sh
- ui/frontend/package.json
This is the latest LTS version.
> Update to Node v14.15.1

- top-crates/src/main.rs
> Note: if the maintainers/owners of `rust-playground` had any interest in publishing `rust-playground/top-crates` to crates.io, that would be super appreciated and this PR would make it really easy to do that!! 
Over at [`optopodi`](https://github.com/optopodi/optopodi), we're hoping to utilize the code found in `top-crates/src/main.rs` to generate the `crate-information.json` automatically — this PR would allow for others to easily reuse this code, too!
> Allow passing an argument to top-crates for the base directory

- .github/workflows/ci.yml
- .github/workflows/cron.yml
- ci/workflows.yml
https://github.com/docker/buildx/issues/834#issuecomment-965730742
> Pin to buildkit 0.9.1 in an attempt to mitigate problems

- .github/workflows/ci.yml
- ci/workflows.yml
> Attempt to avoid "not authorized to perform: sts:TagSession"

- README.md
- ui/README.md
- ui/src/env.rs
- ui/src/main.rs
As proposed in https://github.com/integer32llc/rust-playground/pull/816#issuecomment-1163983884.
> Make PLAYGROUND_UI_ROOT optional

- compiler/base/Cargo.toml
- compiler/base/crate-information.json
- compiler/base/modify-cargo-toml/Cargo.lock
- top-crates/Cargo.lock
Update top crate list with `top-crate` binary to resolve #858.
Tested on local fork. See attached images for difference after update.
> Update top crate list

- ui/frontend/package.json
- ui/frontend/yarn.lock
> Rollback react-monaco-editor to reduce flicker

- ui/frontend/websocket.ts
> Report WebSocket errors that occur after construction

- ui/src/metrics.rs
> Namespace playground WebSocket metrics

- ui/frontend/index.tsx
> Enable WebSocket connection for everyone

- ui/frontend/.eslintrc.js
- ui/frontend/.prettierignore
- ui/frontend/PopButton.module.css
- ui/frontend/PopButton.tsx
- ui/frontend/package.json
- ui/frontend/yarn.lock
This has the nice benefit of better accessibility, hooray!
> Replace popper with floating-ui

- ui/frontend/reducers/websocket.ts
- ui/frontend/websocketMiddleware.ts
- ui/src/server_axum/websocket.rs
As identified by @aguspdana, the original implementation attempted to reconnect every so often, even if other connection attempts were still in progress! This could lead to a situation where multiple WebSockets were connected, which could explain the recent surge in connections we saw *after* the incident where the server could not respond.
> Wait for a WebSocket connection to close before reconnecting

- tests/spec/support/matchers/be_at_url.rb
Hopefully this fixes that nasty flaky failure for good!
> Use Capybara waiting for URL tests

- ui/frontend/Help.tsx
In #962 I accidentally introduced a missing space, this hopefully fixes that
> Fix mistake in #962 that introduced a missing space

- tests/spec/features/test_action_spec.rb
- ui/frontend/actions.ts
> Use the provided crate type when running tests

- ui/frontend/Help.tsx
Thanks for always maintaining rust-playground!
I found some outdated links and have corrected them.
> Update outdated links

- compiler/base/orchestrator/src/worker.rs
If the program outputs a little bit of UTF-8 content and then a bunch on non-UTF-8 content, it's possible that we'd have 4 or more incomplete bytes. This means that the previous assertion was overzealous.
> Deal with non-UTF-8 bytes after valid UTF-8 bytes

- compiler/base/orchestrator/src/coordinator.rs
During a recent outage, the Docker service reported 161 running `docker` processes, while the playground was only aware of 27. Each `docker` processes (and their children) use about 30 MiB of RAM. That would total 4.7 GiB of memory, while the instance only has 4GiB.
My hypothesis is that we are starting containers, then encountering an error and bubbling it up to the caller. Along the way, we skip the call to shutdown the container.
This change tries to shutdown the container when the value is dropped. This should allow it to be handled in error cases as well.
It's possible that this might also help with some of the zombie processes we see from time-to-time!
> Try to more thoroughly kill child Docker processes

- compiler/base/orchestrator/src/coordinator.rs
This should help correlate log messages
> Track the container name to kill

- .github/workflows/ci.yml
- ci/Dockerfile
There's some exciting deadlock occurring in production. Hopefully this
will allow me to glean some kind of information about it...
> Build the backend service with debug symbols

- CRATE_POLICY.md
A draft-like. (Related to #1130.)
Feel free to edit. Suggest to keep links to the past issues & their relevant comments in, so that people can see context.
> Explanation about crate version upgrades.
