rust-lang/rust-playground

- ui/README.md
I found that the README file in the UI directory is not able to be correctly rendered on Github. I guessed you might want to put a table in the file.
So I corrected the format of the table in order to make it display correctly.
> Correct the format of the README in UI directory

- ui/frontend/webpack.config.js
This will allow us to load the entire brace library to get all the
themes and keyboard handlers without overly bloating the app chunk.
This is complicated because the vendor chunk includes the manifest by
default. Since the manifest changes every time the application code
changes, that's not very useful! Large thanks go to [SurviveJS] for
pointers towards the proper setup.
[SurviveJS]: http://survivejs.com/webpack/building-with-webpack/splitting-bundles/
> Create a vendor chunk

- ui/Cargo.toml
- ui/src/sandbox.rs
That way it is possible to not use this flag by building like so:
`cargo build --no-default-features`
This is useful for local sandbox installations running on a different
OS which doesn't directly support limiting PIDs, or which works
differently in that regards.
I am using coreOS for example, but admittedly also didn't try
to find a way to make it work.
> Make `--pids-limit` a default feature

- ui/frontend/package.json
- ui/frontend/yarn.lock
Although it's an optional dependency of upstream, we always want to use
it, so it's not optional for us.
> Correctly require node-zopfli

- tests/spec/features/sharing_with_others_spec.rb
It's really difficult to test permalinks because the page should
essential remain unchanged. It's easier to make sure things worked if we
deliberately go somewhere else (a blank page, for example) and then come
back.
> Update gist test to navigate away before following links

- ui/src/sandbox.rs
Adding these arguments should make it significantly more difficult to break out of the sandbox.
Documentation links:
- https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
- http://www.projectatomic.io/blog/2016/03/no-new-privs-docker/
Note that play.rust-lang.org [already uses these options](https://github.com/rust-lang/rust-playpen/blob/ac799f6f69389ca68bbc52f46a8956938c06317e/src/docker.rs#L22-L26).
> launch sandbox with --cap-drop=ALL and --security-opt=no-new-privileges

- ui/Cargo.toml
- ui/src/main.rs
This is a sequel to #114 . After your suggestions I had a look at existing CORS libraries for Iron to see if I could use them to make a more correct implementation of CORS for the playground. I concluded that there was definitely room for a more ambitious CORS library, so I totally rabbit-holed and went ahead and wrote it myself. 
In order to minimize the amount of CORS code in the playground, I used a single config for all endpoints.
> Cors Again

- ui/frontend/Configuration.jsx
- ui/frontend/Playground.jsx
- ui/frontend/actions.js
- ui/frontend/index.scss
- ui/frontend/local_storage.js
- ui/frontend/reducers.js
As discussed in issue #162, there is now an automatic option, too. I tried to fix the the margins, but the current CSS solution is hacky and I think this should be revisited. Perhaps when adding the rotation for the hidden tab buttons in vertical split mode? I just added the split configuration for now because it has higher priority.
I'll be happy about feedback :)
Add an option in the configuration menu to change the split behaviour
/ orientation between "Automatic" (similar to the old playground),
"Horizontal" (the current behaviour of the integer32llc playground) and
"Vertical" (similar to the old playground for widescreen displays)
- Add changeOrientation and orientation to the props of Configuration
- Add a new ConfigurationSelect-instance in the Configuration
componenent
- Add said …
> Add configurable split behaviour

- ui/.gitignore
- ui/frontend/gist.js
Hi all
I noticed that all my gist links (eg. [this](https://play.rust-lang.org/?gist=828d338bf3cb4214a8127786d89fe085&version=stable) or [that](https://play.rust-lang.org/?gist=363d161c570fef39b555f6e08c8f7d00&version=stable&backtrace=2)) were broken because I use a more specific filename than `playground.rs`.
With this fix the UI will load the last/only file inside a gist so any name can be chosen.
Best
> Load code from gist.github.com with any filename

- ui/frontend/AdvancedEditor.tsx
- ui/frontend/advanced-editor.ts
- ui/frontend/rust-playground-mode.ts
- ui/frontend/webpack.config.js
Pleasantly, we should see a production size decrease from 340K to 249K and 4 fewer requests (w/ emacs & github), since `brace` is no longer duplicated and more async things are in one bundle.
> Use new keyword highlighting rules

- ui/src/asm_cleanup.rs
The assembler directive screening added in 9c495af2ce660c2253e4ea97562f52559cf5a93f is removing labels as well as directives from the assembly.  As labels are needed to understand code flow, this is bad.  This change prevents labels from being removed when assembler directives are screened out. 
A future enhancement I'd like to try is to only display labels that are used, which is the default on Godbolt, but that is a more complex change and it's better to resolve this issue quickly.
**New - Labels Retained**
```asm
.LBB0_2:
movl	$0, -48(%rbp)
jmp	.LBB0_4    ;Target of jmp is defined
.LBB0_4:
movq	-48(%rbp), %rax
```
**Existing - Labels Removed**
```asm
movl	$0, -48(%rbp)
jmp	.LBB0_4     ;No definition of .LBB0_4, unclear where jmp goes
movq	-48(%rbp), %rax
```
> Fix labels being removed from asm

- ui/frontend/Configuration.tsx
- ui/frontend/actions.ts
- ui/frontend/local_storage.ts
- ui/frontend/reducers/configuration.ts
- ui/frontend/types.ts
- ui/src/asm_cleanup.rs
- ui/src/main.rs
- ui/src/sandbox.rs
This adds more thorough filtering and formatting to the assembly view, removing unused labels and keeping relevant data directives.
The "Assembler Directives" option in the Configuration menu is renamed to a more generic "Assembly View," as more than just directives are being removed now.  Internally, "hideAssemblerDirectives" is changed to "processAssembly" for the same reason.
**New**
```asm
playground::main:
subq	$56, %rsp
leaq	ref.2(%rip), %rax
movq	%rax, 8(%rsp)
str.1:
.ascii	"Hello, world!\n"
ref.2:
.quad	str.1
.quad	14
```
**Current**
```asm
playground::main:
subq	$56, %rsp
.Lcfi0:
leaq	ref.2(%rip), %rax
movq	%rax, 8(%rsp)
.Lfunc_end1:
str.1:
ref.2:
```
> Added filter for used labels and data directives in assembly

- top-crates/src/main.rs
Apologies for the onslaught of pull requests lately, but this one should resolve the underlying problem from #252.
I found that incremental compilation will disregard the value of codegen-units, causing multiple output files to be created when using -o foo --emit=bar.  This was why the issue only occurred in nightly and beta debug, stable rustc and release builds do not use incremental compilation.
I opened rust-lang/rust#48147 to rustc, but we can mitigate the issue for the playground immediately by disabling incremental compilation via Cargo.toml.
> Disable incremental compilation to resolve issue 252

- compiler/clippy/Dockerfile
Now that Clippy uses `cargo check`, we can't rely on the existing
build artifacts from our base container.
> Prebuild Clippy build artifacts

- README.md
This updates the "Build and run the server" section of the readme to include the new required environment variable PLAYGROUND_GITHUB_TOKEN .
> Added PLAYGROUND_GITHUB_TOKEN to Build and run the server instructions

- ui/src/gist.rs
When you import a gist with multiple files via url, $ is added at the beginning of each file, which causes compilation error:
https://github.com/integer32llc/rust-playground/issues/289
So this change fixes the problem.
> Removes $ sign when importing gist with multiple files

- ui/frontend/index.scss
We are using React-Portal to add the Popper.js Poppers to the DOM. By
default, these are added at the end of the `<body>` tag. Since our
content takes up the entire page, adding them causes the scrollbars to
appear momentarily, which Popper.js uses in the calculations. When the
popper is moved to the right place, the scrollbar disappears, and the
popper has to move a second time.
We "fixed" this by disabling the scrollbars completely, forgetting
about the help page. This fixes it by positioning the popper so it
doesn't cause the scrollbars to appear to start with.
Closes #304
> Restore scrolling of the help page

- ui/frontend/PopButton.tsx
The default GPU-accelerated transforms used for positioning made text rendering blurry in certain configurations of browsers and cleartype settings on Windows.
Fixes #303
> Switch Poppers to transform-less positioning

- top-crates/src/main.rs
The "playground" feature is superseded by Cargo.toml custom metadata from #326.
The last of the top 100 crates still using this feature is uuid. I have a PR open in https://github.com/uuid-rs/uuid/pull/224 to move them to custom metadata. I don't think we need to wait for them because the playground feature doesn't do what they want anyway. The features were enabled during transitive dependency resolution but not in the Cargo.toml generated by top-crates. For example see [this playground](https://play.rust-lang.org/?gist=40ff2a86635c432ab14c48e74372dd98) which shows uuid's `"serde"` feature not enabled despite being listed as a playground feature [here](https://github.com/uuid-rs/uuid/blob/0.6.3/Cargo.toml#L46).
> Remove enabling a "playground" feature

- ui/src/sandbox.rs
This commit fixes errors on a number of sandbox tests. An edition was added to all compile and execute request tests; stable channel tests received a value of None, the nightly test uses Edition::Rust2018.
In addition, Clippy has changed the ['eq_op' lint](https://rust-lang-nursery.github.io/rust-clippy/current/index.html#eq_op) from warn to deny. Updated the 'linting_code' test to expect this.
> Fix failing sandbox tests due to missing edition

- tests/spec/features/backtrace_spec.rb
- ui/frontend/AdvancedOptionsMenu.tsx
- ui/frontend/actions.ts
- ui/frontend/highlighting.ts
- ui/frontend/index.tsx
- ui/frontend/reducers/configuration.ts
- ui/frontend/selectors/index.ts
- ui/frontend/types.ts
- ui/src/main.rs
- ui/src/sandbox.rs
> Allow enabling backtraces

- .travis.yml
- compiler/build.sh
- compiler/fetch.sh
- compiler/miri/Dockerfile
- compiler/miri/cargo-miri-playground
- tests/spec/features/tools_spec.rb
- ui/frontend/Help.tsx
- ui/frontend/Output.tsx
- ui/frontend/ToolsMenu.tsx
- ui/frontend/actions.ts
- ui/frontend/reducers/output/index.ts
- ui/frontend/reducers/output/meta.ts
- ui/frontend/reducers/output/miri.ts
- ui/frontend/selectors/index.ts
- ui/frontend/types.ts
- ui/src/main.rs
- ui/src/sandbox.rs
> Add Miri as a tool

- .travis.yml
- compiler/miri/Dockerfile
However, I am not sure if I got that travis syntax right and their validator is deprecated without replacement... I guess we'll see in the PR's travis run?
Fixes https://github.com/integer32llc/rust-playground/issues/387
> Fix miri build process

- ui/frontend/ToolsMenu.tsx
- ui/frontend/actions.ts
- ui/frontend/index.scss
- ui/frontend/reducers/versions.ts
- ui/frontend/selectors/index.ts
- ui/src/main.rs
- ui/src/sandbox.rs
> Show versions of tools.

- ui/src/sandbox.rs
This PR unconditionally enables assembly comments when the compiler supports them (nightly only, for now).
These comments can provide useful information, such as:
- inform about register spills
- specify the depth of a label in a loop
```asm
.LBB0_10: ; =>This Inner Loop Header: Depth=1
```
- what happens to SIMD lanes in shuffles
```
pshufd  xmm1, xmm0, 78 ; xmm1 = xmm0[2,3,0,1]
```
Fixes #397.
> Enable -Z asm-comments on nightly

- ui/src/asm_cleanup.rs
Fixes #406 
The LLVM comments recently added to assembly are not handled by the existing filtering scripts, causing some labels to be removed incorrectly.
This commit makes the following updates:
* Fixes the assembly filtering to recognize labels with a comment on the same line
* Retain comments that are on their own line
* For now I've  retained the `# %bb` comments as seen in the example below.  I'm not sure how much utility they provide, but they also don't create too much noise.
* Directive types that were previously removed will continue to be removed even if they have a comment
* This removes the "Begin function..." comments added to `.p2align` directives, but still retains the standalone "End function" comments.  I don't think this will be confusing as the filtering makes it easy …
> Update assembly filter to handle LLVM comments

- ui/frontend/actions.ts
- ui/frontend/highlighting.ts
- ui/frontend/index.tsx
- ui/frontend/reducers/code.ts
close #317
When error message contains help hint as below,
```
error[E0658]: non-ascii idents are not fully supported. (see issue #28979)
--> src/main.rs:4:9
|
4 |     let α = 0.00001f64; // #![feature(non_ascii_idents)]
|         ^
|
= help: add #![feature(non_ascii_idents)] to the crate attributes to enable
```
Highlight `add #![feature(non_ascii_idents)]` and provide a clickable link to insert code at  the first line to enable corresponding feature gate.
Output standard error are highlighted as following image. It seems a bit dumb. Maybe click-to-add anchors need additional styling?
I cannot figure out how to bootstrap Ruby environment to run rspec. Therefore, this feature only be tested manually. Below is a valid test case.
```rust
const X: u8 = { let x = 1; x }; // …
```
> Click help hint link to enable feature gate

- ui/frontend/reducers/code.ts
We changed from string concatenation to string interpolation in https://github.com/integer32llc/rust-playground/pull/415.
With using string interpolation, we don't need the single quote now and it will cause the `fn` to be `'fn`.
| As is | To be |
| ----- | ----- |
| <img width="326" alt="default" src="https://user-images.githubusercontent.com/6782666/46809772-cdbdd900-cda1-11e8-8f66-7140b9bba13d.png"> | <img width="317" alt="default" src="https://user-images.githubusercontent.com/6782666/46809814-e8904d80-cda1-11e8-80b9-e6662f65b1bc.png"> |
> Remove typo single quote for adding main function

- ui/frontend/Output/Gist.tsx
- ui/frontend/selectors/index.ts
Hey maintainers, this is my first contribution to rust-playground. If I did something inappropriate or violating any rule, just tell me directly. Thanks.
`code` querystring is an awesome feature to share code instantly without generating additional gist. Hence, I implemented a proof of concept that copying URL with `code` query. Currently, this feature is placed in **Gist.tsx** component behind the **SHARE** button. If you consider this helpful, I am willing to complete it in an independent UI without creating any gist.
1. Click SHARE button
2. Click copy icon right after **Embedded code in link**.
Although some browsers may set a maximum length limit on their URL location bar, it seems that Firefox and Chrome support at least 10k lines of code. Here are screenshots of my manual tests on …
> Feature: copying embedded code link

- compiler/miri/cargo-miri-playground
With https://github.com/solson/miri/pull/488 merged, `-Zmiri-start-fn` no longer exists as a parameter.
> -Zmiri-start-fn is gone

- compiler/miri/Dockerfile
- compiler/miri/cargo-miri-playground
`cargo miri` now automatically installs xargo and the rust-src component and builds libstd. `cargo miri setup` is a way to do only that, and without interactive questions.
When actually executing the file, we set the `MIRI_SYSROOT` env var manually. That is not needed, but it makes sure that the automatic setup part is skipped (it shouldn't do anything anyway).
> update for miri's new automatic libstd build

- compiler/miri/cargo-miri-playground
Miri now supports system-seeded RNGs but simulates them with a fixed seed that needs to be passed on the command-line.
> pass a seed to Miri so that HashMaps work

- ui/src/main.rs
This adds the `edition` and `tests` fields to the `/evaluate.json` endpoint.  This is so that mdBook can start using them.
Closes #486
> Add edition and tests fields to /evaluate.json

- ui/frontend/AdvancedEditor.tsx
- ui/frontend/types/ace-builds.ts
We need to preserve our current selection state when Redux drives the
update. It would be good to figure out *why* this update is occurring
though...
Closes #494
> Prevent the cursor from jumping to the end of the file

- ui/src/gist.rs
When multiple gist is imported, there is a trailing whitespace between the comment representing filename and the code, giving a sense of disjointedness:
```
// Imlementation.rs
fn greet(s: &String) -> String {
format!("Hello {name}!", name=s)
}
```
Here is a live demo:
https://play.rust-lang.org/?gist=1f059252234606216cf8721209456287&version=stable
This commit removes the trailing whitespace after the filename.
> Remove trailing whitespace for multiple gist embed

- compiler/miri/cargo-miri-playground
With https://github.com/rust-lang/miri/pull/851, this is the default.
> miri no longer needs -Zmiri-seed

- ui/frontend/highlighting.ts
Fix #505
| Before | After |
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/6782666/60859513-f221e580-a24d-11e9-9f5c-f523bfe0f743.png) | ![image](https://user-images.githubusercontent.com/6782666/60859518-f948f380-a24d-11e9-98b8-6ba829f4f4ff.png) |
> Fix highlight for warnings with error number

- ui/frontend/index.scss
You still have to start the drag from off of the button, but it's
better.
> Allow selecting the menu button's text

- ui/frontend/selectors/index.spec.ts
- ui/frontend/selectors/index.ts
This adds support for an `async main` function. It updates the regex and tests per #563. It does not check for `#[tokio::main]` or another macro to see if its a properly configured `main` function.
I have not tried running the tests but it seems like they should pass.
> Add support for async main function

- tests/Gemfile.lock
- tests/spec/features/assistance_spec.rb
- ui/frontend/actions.ts
- ui/frontend/highlighting.ts
- ui/frontend/index.tsx
- ui/frontend/reducers/code.ts
In this PR, the frontend detects import suggestions in compiler output and makes them clickable. On click, the suggestion is inserted at the top of the editor.
Inserting imports at the beginning is not ideal. Ideally, the new import should go at the end of the imports block, and the imports block should be separated from items with an empty line. Also it won't work if the compile error originates from a nested module. However, the frontend doesn't seem to have tools for more sophisticated behavior, and this implementation greatly simplifies preparing a working snippet the most common case.
Closes #404.
> Make import suggestions clickable

- tests/spec/features/highlighting_error_output_spec.rb
- tests/spec/features/tools_spec.rb
- ui/frontend/Output.tsx
- ui/frontend/ToolsMenu.tsx
- ui/frontend/actions.ts
- ui/frontend/reducers/output/index.ts
- ui/frontend/reducers/output/macroExpansion.ts
- ui/frontend/reducers/output/meta.ts
- ui/frontend/selectors/index.ts
- ui/frontend/types.ts
- ui/src/main.rs
- ui/src/sandbox.rs
This PR add new tool "Macro expand" to Playground  (#158). Under the hood it call `cargo run -- --Zunstable-options --pretty=expanded` with nightly compiler.
How it looks:
> Add "Macro expand" tool to Playground

- tests/spec/features/highlighting_mir_output_spec.rb
- tests/spec/support/editor.rb
- ui/frontend/AdvancedEditor.tsx
- ui/frontend/Editor.tsx
- ui/frontend/Output.tsx
- ui/frontend/Output/PaneWithMir.tsx
- ui/frontend/actions.ts
- ui/frontend/highlighting.ts
- ui/frontend/index.tsx
- ui/frontend/reducers/index.ts
- ui/frontend/reducers/selection.ts
- ui/frontend/types.ts
> Link MIR output to the original code

- ui/frontend/index.scss
The playground height does not fit into its parent height, so the extra scrolling happens.
This PR changes playground height to 100% to match the parent view height.
Before:
After:
> fix: fit the playground height to the parent view height

- ui/frontend/index.ejs
these accessibility issues were low-hanging fruit, so addressing in one commit:
- add a lang attribute to the html element
- add a meta description (also counts for the SEO lighthouse score)
- add a landmark (main) to the page
> fix some a11y issues

- compiler/miri/cargo-miri-playground
The old `cargo miri` does not work any more, the subcommand must be given explicitly.
(The only reason Miri works on the the playground website right now is that it is using an outdated Miri.)
> explicitly use 'cargo miri run'

- ui/frontend/highlighting.ts
Otherwise it would highlight too much of the line if there were multiple MIR
sources. For example with [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=30970d3e39b0bfcba0120b04385da47e), it would highlight the line like this:
> let mut _0: \[closure@[src/main.rs:6:5: 6:23 y:i32\]; // return place in scope 0 at src/main.rs:5:19: 5:38]()
> Stop the MIR source regex from being greedy

- tests/Gemfile
- tests/Gemfile.lock
- tests/spec/features/highlighting_error_output_spec.rb
- ui/src/sandbox.rs
> Increase default memory limits

- tests/spec/features/sharing_with_others_spec.rb
- ui/frontend/Output/Gist.tsx
- ui/frontend/selectors/index.ts
Fixes https://github.com/integer32llc/rust-playground/issues/671
Didn't test this locally because the frontend doesn't build on my machine
> Remove "Open an issue" link

- ui/frontend/Playground.module.css
- ui/frontend/Playground.tsx
Since we were rotating the *entire* gutter, it would easily extend
beyond the window boundaries, adding a scrollbar to the entire
playground. Instead, rotate only the handle icon itself. Due to [a
limitation with split.js][limitation], we have to also ignore pointer
events on the handle since it's now a child of the gutter.
[limitation]: https://github.com/nathancahill/split/issues/354
> Prevent expanding the window size when adjusting the split

- ui/src/sandbox.rs
I'm considering removing `--pretty` in https://github.com/rust-lang/rust/pull/83491, which would break playground. If we decide #83491 should go forward, this unblocks it.
> Use `--unpretty=expanded` instead of `--pretty`

- compiler/base/modify-cargo-toml/src/main.rs
- ui/src/sandbox.rs
It was only needed until the 2021 edition was stabilized in cargo, and this has been done on nighty and beta. 
We can see a warning cargo currently emits when using the edition 2021 on the playground, and this PR should fix that.
> Remove special case for cargo "edition2021" feature

- ui/frontend/.eslintrc.js
- ui/frontend/editor/MonacoEditorCore.tsx
- ui/frontend/editor/rust_monaco_def.ts
- ui/frontend/webpack.config.js
> Fix Monaco bugs

- .github/workflows/ci.yml
- ci/workflows.yml
- top-crates/src/lib.rs
- top-crates/src/main.rs
I was touching `top-crates` and noticed that rustfmt makes a bunch of unrelated modifications. Formatting is enforced elsewhere in this codebase (for the `ui` crate) so I'm adding the same here for `top-crates`.
> Format top-crates crate with rustfmt and check in CI

- top-crates/Cargo.lock
- top-crates/Cargo.toml
- top-crates/src/lib.rs
Prior to this, top-crates would serialize version reqs like this:
```toml
[dependencies.foo]
package = "foo"
version = "=1.2.3+whatever"
```
which would then stick a warning into the output every single time the playground compiles anything, whether or not that crate was ever used.
```console
warning: version requirement `=1.2.3+whatever` for dependency `foo` includes
semver metadata which will be ignored, removing the metadata is recommended
to avoid confusion
```
Note that we'll still keep the build metadata in generated crate-information.json, just not in Cargo.toml.
> Omit build metadata from versions in generated Cargo.toml

- ui/README.md
- ui/src/env.rs
- ui/src/main.rs
- ui/src/server_axum.rs
I am working on a PR for something totally unrelated to gists, and didn't want to bother setting up a GitHub token just so that the server wouldn't crash on startup.
> Make PLAYGROUND_GITHUB_TOKEN optional

- compiler/base/Cargo.toml
- compiler/base/crate-information.json
- top-crates/src/lib.rs
- top-crates/src/main.rs
This is a substantial refactor of `top-crates` (but split up into easy commits for review).
Basically the playground was previously redundantly building multiple redundant versions of lots of crates redundantly. In the case of the following dependency graph:
- `playground`
- normal dependency on `A`
- normal dependency on `C` with no features
- dependency on `B` (proc macro)
- build dependency on `C` with feature `x`
cargo would build 2 copies of `C`, with and without the feature `x` enabled, because one is for the "target" and one is for the "host", even though in the context of the playground the "target" and "host" are the same architecture and one shared copy of `C` would have been fine.
If `C` is somewhere way deeper in the dependency graph (like `proc-macro2`, which was affected by …
> Speed up base build and shrink image

- compiler/miri/cargo-miri-playground
The miri sysroot moved, so this hard-coded location needs to be updated.
> fix miri sysroot location

- README.md
https://github.com/integer32llc/rust-playground/pull/799 changed the backend from Iron to Axum - but the readme still had Iron listed. This personally threw me off as I went off investigating what Iron is as a result.
> Changed mentions of Iron to Axum

- tests/spec/features/navigation_spec.rb
- tests/spec/features/sharing_with_others_spec.rb
- tests/spec/support/matchers/be_at_url.rb
- ui/frontend/Output/Gist.tsx
- ui/frontend/Router.tsx
- ui/frontend/selectors/index.ts
After we've clicked 'Share' and a Gist has been created, update the address bar with the permalink to the shared playground.
I'm not very familiar with React, so apologies if this isn't the idiomatic way to do this.
> Update address bar after saving Gist

- tests/spec/features/tools_spec.rb
- ui/Cargo.lock
- ui/Cargo.toml
- ui/frontend/declarations.d.ts
- ui/frontend/index.tsx
- ui/frontend/websocket.ts
- ui/src/metrics.rs
- ui/src/server_axum.rs
Added metrics for number of active sessions and sessions' durations based on websockets' connectivity. 
And tested them with local Prometheus server.
> Add metrics for number of active sessions and sessions' durations

- tests/spec/features/highlighting_error_output_spec.rb
- ui/frontend/highlighting.ts
This updates the hyperlinks for error codes to point to the new error index locations (as updated in rust-lang/rust #100922). For example, what used to link to `https://doc.rust-lang.org/stable/error-index.html#E0005` will now link to `https://doc.rust-lang.org/stable/error_codes/E0005.html`. Currently, a redirect makes this work fine, but it's probably best to use the new locations.
> update error-index hyperlinks

- ui/frontend/websocketMiddleware.ts
After deploying the WebSocket reconnection logic, our total connection count slowly grew until nginx stopped being able to handle new connections, leading to a severely degraded experience.
Closing the WebSocket for idle consumers should reduce the concurrent connection count. Eventually we will need to handle re-starting the connection anyway (and potentially only starting it on demand).
> Disconnect the WebSocket after an idle period

- compiler/base/Dockerfile
- compiler/base/attach_notice.sh
- compiler/base/security_notice.txt
- tests/spec/features/security_spec.rb
I've added a fairly generic script that allows to include any text file to any other text file, either on top or on the bottom, based on the arguments passed during the execution (just in case a similar need arie in the future for another use case). 
I've also updated the Dockerfile to execute the script at the end (before the entrypoint). Since the intention was to modify `/etc/passwd` and `/etc/shadow` files, I had to change the `USER` to `root` temporarily. After the files are updated, I changed the user back to `playground`.
The security notice I copied as is from #626. 
The updates are done from `/tmp` folder and at the end the script is removed. However, I decided to leave the security notice itself in the `playground` folder: `/playground/security_notice.txt` so that as soon as …
> Add a security notice to commonly inspected files

- ui/frontend/package.json
- ui/frontend/yarn.lock
Something has changed in 1.23 with how themes and keybindings are packaged, causing them to not work with our interesting setup. Rolling back while we investigate.
Reported in #941
> Downgrade to Ace 1.22.1

- ui/frontend/package.json
- ui/frontend/webpack.config.js
- ui/frontend/yarn.lock
Ace 1.23 introduces `theme-${name}-css.js` files alongside the existing `theme-${name}.js` files. These files only define the CSS (as suggested by their name) and so aren't valid as theme choices. The existing files include both the JS and CSS. Filter out the new files from our theme choices.
Closes #941
> Upgrade to Ace 1.23.1

- ui/frontend/Playground.tsx
- ui/frontend/actions.ts
- ui/frontend/editor/AceEditor.tsx
- ui/frontend/editor/AceEditorCore.tsx
- ui/frontend/reducers/browser.ts
- ui/frontend/selectors/index.ts
- ui/frontend/types.ts
[Ace added a `ResizeObserver`][pr-5095] to automatically perform resizes as needed, so we can remove our junk — hooray!
[pr-5095]: https://github.com/ajaxorg/ace/pull/5095
> Remove our code that triggered Ace resizes

- ui/frontend/index.tsx
- ui/frontend/package.json
- ui/frontend/yarn.lock
This is easy enough to support, even though it's outside of our support window.
Closes #957
> Support Firefox 91.13.0esr which does not provide crypto.randomUUID

- ui/frontend/Help.tsx
`extern crate` is no longer necessary in most cases since Rust 2018
This PR adds a clarification to the help page
> Clarify suggestion to use extern crate in help

- compiler/base/orchestrator/src/coordinator.rs
- ui/src/main.rs
- ui/src/server_axum.rs
- ui/src/server_axum/websocket.rs
This will help reduce the sheer number of PIDs we create, as well as
hopefully reduce memory pressure a little bit.
> Create each channel's container lazily

- compiler/base/orchestrator/src/coordinator.rs
Otherwise, the token stays canceled and all subsequent attempts to spawn a child immediately exit.
Fixes #974
> Replace the CancellationToken with a new one when idling

- ui/frontend/Output/SimplePane.tsx
> Prevent output pane text from being copied as HTML

- compiler/base/orchestrator/src/coordinator.rs
- ui/src/sandbox.rs
play.rust-lang.org has had a few outages because the machine is a bit low on memory and the OOM killer picks to reap nginx. There are many containers running using a small amount of memory while the one nginx uses more, so it's a more attractive target.
My ideal situation would be if we could group all the containers and kill from that pool until the memory pressure is resolved, but I don't know how to do that.
> Encourage the OOM killer to pick the container processes

- compiler/base/modify-cargo-toml/src/lib.rs
- compiler/base/modify-cargo-toml/src/main.rs
- compiler/base/orchestrator/src/coordinator.rs
- tests/spec/features/editions_spec.rb
- ui/frontend/AdvancedOptionsMenu.tsx
- ui/frontend/actions.ts
- ui/frontend/types.ts
- ui/src/main.rs
- ui/src/sandbox.rs
- ui/src/server_axum.rs
- ui/src/server_axum/websocket.rs
> Support Rust edition 2024

- compiler/base/orchestrator/Cargo.toml
- compiler/base/orchestrator/src/coordinator.rs
- ui/Cargo.lock
We stream messages from the coordinator to the worker via stdin/stdout piped to `docker run`. However, sometimes we close the pipe corresponding to `docker run`'s stdout before it has had a chance to fully write everything. If that happens, `docker run` exits without deleting the container [1].
This has likely always been a problem with the coordinator / worker architecture, but it's exacerbated by the recent addition of the memory / CPU status messages that occur every second, which greatly increase the amount of data crossing the boundary.
This reorganizes the code to pass in a known reasonably unique name to the container and then attempts to kill that container at cleanup time.
I tested by:
- Setting the worker status interval to 16ms (from 1s)
- Setting the webserver idle interval to …
> Kill the container ourselves when done

- compiler/base/Cargo.toml
- compiler/base/crate-information.json
- compiler/base/modify-cargo-toml/Cargo.lock
- compiler/base/orchestrator/Cargo.lock
- top-crates/src/main.rs
- ui/Cargo.lock
The change is compatible. Just prepare for edition 2024 in advance.
See also:
* <https://github.com/rust-lang/cargo/issues/13629>
* <https://github.com/rust-lang/cargo/pull/13783>
* <https://github.com/rust-lang/cargo/pull/13798>
* <https://github.com/rust-lang/cargo/pull/13804>
> fix: use kebab-case as underscores are not allowed in edition 2024

- compiler/base/orchestrator/Cargo.toml
- compiler/base/orchestrator/src/coordinator.rs
- ui/src/server_axum/websocket.rs
Each `Coordinator` can have 0-3 backends running as it abstracts over {stable,beta,nightly} and each backend is lazily created and idled.
The "good" failure case was that we could be off by a factor of 3 in the upper bound. The catastrophic failure case was for the WebSocket connections where there are thousands of `Coordinator`s idling with very few of them actively compiling at a time. Setting a low limit would prevent connections, setting a high limit was basically pointless.
> Limit concurrency of active backends, not Coordinators

- compiler/base/orchestrator/src/coordinator.rs
- ui/src/main.rs
- ui/src/metrics.rs
- ui/src/public_http_api.rs
- ui/src/sandbox.rs
- ui/src/server_axum.rs
- ui/src/server_axum/websocket.rs
The queue depth is no longer represented by the time taken to create
the `Coordinator` — that depth is now buried inside implementation
details — so I'm removing the metric.
> Creating the Coordinator is no longer async

- compiler/base/orchestrator/src/coordinator.rs
- compiler/base/orchestrator/src/coordinator/limits.rs
- ui/src/main.rs
- ui/src/metrics.rs
- ui/src/server_axum/websocket.rs
This also fuses together the unique ID generation with resource concurrency limits.
As part of this, we expose some hooks that we can use to provide metrics about how many people are waiting for containers / processes.
> Introduce limits for number of active processes

- compiler/base/orchestrator/src/coordinator.rs
This option was recently renamed, so the playground's assembly output is broken on the nightly channel. See <https://github.com/rust-lang/rust/pull/126803#event-13384747335>.
> Change `asm-comments` to `verbose-asm`

- top-crates/crate-modifications.toml
In the upcoming async chapter, because the standard library doesn't include an async runtime, we need to use crates.
To make it easier to manage versions and updates, we've created a shim crate named `trpl` that mostly re-exports relevant parts of other crates in a way that we can control, to ensure the best experience for book readers.
While this crate may organically end up in the most-used crates included in the playground *eventually*, we'd love for the `trpl` crate to be available in the playground for readers before the chapter is officially published.
Thank you! ❤️
> Add the trpl crate to support The Book exercises

- ui/src/server_axum.rs
When running the server, I noticed IP/port info of the Axum server were not shown.
Running `RUST_LOG=info` will show this now.
> Display Axum server IP and Port info with `RUST_LOG=info`

- ui/frontend/.stylelintrc.json
- ui/frontend/BuildMenu.module.css
- ui/frontend/ButtonSet.module.css
- ui/frontend/ButtonSet.tsx
- ui/frontend/ConfigElement.module.css
- ui/frontend/ConfigMenu.tsx
- ui/frontend/Help.module.css
- ui/frontend/Notifications.module.css
- ui/frontend/Output.module.css
- ui/frontend/Output/Header.module.css
- ui/frontend/PopButton.module.css
- ui/frontend/PopButton.tsx
- ui/frontend/configureStore.ts
- ui/frontend/index.module.css
- ui/frontend/index.tsx
- ui/frontend/local_storage.ts
- ui/frontend/package.json
- ui/frontend/pnpm-lock.yaml
- ui/frontend/postcss.config.js
- ui/frontend/reducers/configuration.ts
- ui/frontend/reducers/featureFlags.ts
- ui/frontend/selectors/index.ts
- ui/frontend/shared.module.css
- ui/frontend/types.ts
Fixes https://github.com/rust-lang/rust-playground/issues/544
This uses the media query approach described in the issue. The dark theme I came up with here was created using the [dark reader](https://darkreader.org/) extension and some manual tweaking. I'm not a designer, so happy to change the colors further until it looks acceptable.
> Add dark mode

- ui/frontend/reducers/output/execute.ts
Touches on #1093. We aren't actually timing out, we are just waiting
for a long time. This is a trivial fix, but the bigger fix would be to
indicate that there might be a long wait or offer a deliberate cancel.
> Show the WebSocket execution progress indicator earlier

- ui/frontend/editor/MonacoEditorCore.tsx
As soon as Monaco is instantiated, it measures various aspects of the
chosen font. Since the playground fetches fonts, the fonts may not yet
be available to be measured. After a bit, the fonts are loaded but
Monaco's cached results are now out of date.
We now trigger a remeasurement of the fonts after our fonts are
available.
For some reason, this has only been reported by people using Microsoft
Edge, but theoretically it should occur in any browser. Perhaps
there's something unique about Edge's text rendering? It also only
occurs at certain original zoom levels — on my computer, it needed
125% zoom. Note that each zoom level has different font metrics, so
changing the zoom once the font is loaded will work although the
original incorrect metrics will still be cached.
Fixes #1103
> Ensure Monaco measures fonts after the font is loaded

- compiler/base/orchestrator/src/coordinator.rs
- ui/src/main.rs
- ui/src/server_axum.rs
- ui/src/server_axum/websocket.rs
Two random stabs at solutions:
1. Use `try_join!` in case we are getting stuck in some error case that causes a child future to never exit.
2. Perform an explicit cancelation when the `Coordinator` is dropped.
> More logging and a few attempts at fixes

- compiler/base/orchestrator/src/coordinator.rs
- compiler/base/orchestrator/src/coordinator/limits.rs
- ui/src/server_axum/websocket.rs
We let WebSocket connections keep {stable,beta,nightly} containers
running after the execution finishes. These idle containers still
count against the enforced container limits even though they aren't
doing useful work.
This change allows the owner of those idle containers to know that
someone else wants their slot and then they can make the containers
exit earlier than they otherwise would have.
This can be best shown by setting the container limit very
low (e.g. 2) and then opening that many plus one more browser
tabs (e.g. 3). Before this change, the last tab would need to wait for
the idle timeout (defaults to 60 seconds) before they could have a
chance to run their code.
= Known issues
There's a race that can cause containers to spuriously exit, but that
should only occur when we are …
> Request idling containers exit when the container limit is reached

- compiler/base/orchestrator/src/coordinator.rs
- compiler/base/orchestrator/src/message.rs
- tests/spec/spec_helper.rb
- ui/src/metrics.rs
- ui/src/server_axum.rs
- ui/src/server_axum/cache.rs
This helps prevent a rare suboptimal case where a visitor to the
playground triggered the crates / versions request but then left the
site before the request finished, resulting in the request being
canceled and the work being wasted without being cached. This mostly
showed up when running heavy load tests locally to try and suss out
other bugs.
Other benefits:
- This will also result in reduced contention when multiple requests
would have triggered a cache refresh. Only one computation should
occur.
- The cache value is now computed out-of-band and requests should not
block on it.
> Implement caching via tasks instead of shared mutexes

- compiler/base/orchestrator/Cargo.lock
- compiler/base/orchestrator/Cargo.toml
- compiler/base/orchestrator/src/coordinator.rs
- compiler/base/orchestrator/src/lib.rs
- compiler/base/orchestrator/src/worker.rs
- ui/Cargo.lock
- ui/src/server_axum/cache.rs
- ui/src/server_axum/websocket.rs
When a client disconnects, Axum drops our future. Any tasks we've spawned need to be properly notified to also exit. Enhance tasks to be aborted and cancellation tokens to be triggered when dropped.
I hope that this helps clear up some of the cases where the playground thinks that a container is still running after it has exited.
> Cancel tokens and abort tasks on drop

- ui/frontend/Output/Gist.tsx
I can't even explain the level of embarrassment here.
Fixes #1141
> Actually copy to the clipboard

- compiler/base/cargo-miri-playground
- compiler/base/orchestrator/src/coordinator.rs
- compiler/build.sh
- compiler/fetch.sh
- tests/spec/features/backtrace_spec.rb
- tests/spec/features/tools_spec.rb
- tests/spec/spec_helper.rb
- ui/frontend/.prettierignore
- ui/frontend/AdvancedOptionsMenu.tsx
- ui/frontend/ConfigElement.tsx
- ui/frontend/reducers/configuration.ts
- ui/frontend/reducers/output/miri.ts
- ui/frontend/selectors/index.ts
- ui/frontend/types.ts
- ui/src/metrics.rs
- ui/src/public_http_api.rs
- ui/src/server_axum.rs
Very useful for comparing stacked borrows and tree borrows.
An example for testing:
```rust
fn main() {
let val = [1u8, 2];
let ptr = &val[0] as *const u8;
let _val = unsafe { *ptr.add(1) };
}
```
is valid under Tree Borrows, but not under Stacked Borrows.
UI looks like this:
> Allow user to specify aliasing model for Miri
